import React, { useRef, useState } from 'react';
import { Routes, Route, NavLink, useNavigate } from 'react-router-dom';
import { LayoutDashboard, MessageSquare, Files, Settings, Search, Bell, Plus, Sparkles, ArrowUp, Paperclip, ShieldCheck, FileText, MoreHorizontal, ChevronRight, UploadCloud, CheckCircle2, BookOpen, Scale, Menu, X } from 'lucide-react';

const API = import.meta.env.VITE_API_URL || 'http://localhost:8000';

const nav = [
  {to:'/app', end:true, label:'Overview', icon:LayoutDashboard},
  {to:'/app/chat', label:'Legal assistant', icon:MessageSquare},
  {to:'/app/documents', label:'Documents', icon:Files},
];

function Logo(){ return <a href="/" className="text-lg font-bold tracking-tight">law<span className="text-slate-400">Shield</span></a> }

function Shell({children, title, subtitle, action}){
  const [mobile,setMobile]=useState(false);
  return <div className="h-screen bg-slate-50 flex overflow-hidden">
    <aside className={`${mobile?'flex':'hidden'} md:flex fixed md:static inset-0 z-40 w-full md:w-64 bg-white border-r border-slate-200 flex-col p-4`}>
      <div className="h-12 px-2 flex items-center justify-between"><Logo/><button className="md:hidden" onClick={()=>setMobile(false)}><X size={20}/></button></div>
      <a href="/app/chat" className="mt-4 flex items-center justify-center gap-2 bg-slate-900 text-white text-sm font-semibold rounded-xl py-2.5"><Plus size={15}/> New matter</a>
      <nav className="mt-6 space-y-1">{nav.map(({to,label,icon:Icon,end})=><NavLink end={end} onClick={()=>setMobile(false)} key={to} to={to} className={({isActive})=>`flex items-center gap-3 rounded-xl px-3 py-2.5 text-sm font-medium transition ${isActive?'bg-slate-100 text-slate-950':'text-slate-500 hover:bg-slate-50 hover:text-slate-900'}`}><Icon size={17}/>{label}</NavLink>)}</nav>
      <div className="mt-7 px-3 text-[10px] uppercase tracking-widest font-bold text-slate-400">Recent matters</div>
      <div className="mt-2 space-y-1">{['Patel v. Meridian','Acme Series A review','Motion to suppress'].map(x=><a key={x} href="/app/chat" className="block truncate px-3 py-2 text-xs text-slate-500 hover:text-slate-900">{x}</a>)}</div>
      <div className="mt-auto">
        <div className="rounded-xl border border-slate-200 p-3 mb-3"><div className="flex justify-between text-xs font-semibold"><span>Starter plan</span><span>7 / 10</span></div><div className="h-1.5 bg-slate-100 rounded-full mt-2 overflow-hidden"><div className="h-full w-[70%] bg-slate-900"/></div><p className="text-[10px] text-slate-400 mt-2">Prompts reset in 12 days</p></div>
        <NavLink to="/app/settings" className="flex items-center gap-3 px-2 py-2 rounded-xl hover:bg-slate-50"><div className="w-8 h-8 rounded-lg bg-slate-900 text-white grid place-items-center text-xs font-bold">SC</div><div className="min-w-0 flex-1"><div className="text-xs font-semibold">Sahil Chauhan</div><div className="text-[10px] text-slate-400 truncate">Personal workspace</div></div><Settings size={14} className="text-slate-400"/></NavLink>
      </div>
    </aside>
    <section className="flex-1 min-w-0 flex flex-col">
      <header className="h-16 bg-white/90 backdrop-blur border-b border-slate-200 px-4 md:px-7 flex items-center gap-4 shrink-0"><button className="md:hidden" onClick={()=>setMobile(true)}><Menu size={20}/></button><div><h1 className="text-sm font-bold">{title}</h1>{subtitle&&<p className="text-[11px] text-slate-400">{subtitle}</p>}</div><div className="ml-auto flex items-center gap-2">{action}<button className="w-9 h-9 rounded-xl border border-slate-200 grid place-items-center text-slate-500"><Search size={15}/></button><button className="w-9 h-9 rounded-xl border border-slate-200 grid place-items-center text-slate-500 relative"><Bell size={15}/><span className="absolute top-2 right-2 w-1.5 h-1.5 bg-amber-500 rounded-full"/></button></div></header>
      <main className="flex-1 overflow-auto">{children}</main>
    </section>
  </div>
}

function Overview(){
 const navigate=useNavigate();
 const tools=[['Ask legal AI','Research a question with verified sources',MessageSquare,'/app/chat'],['Analyze a document','Find risks, obligations, and key clauses',FileText,'/app/documents'],['Research case law','Surface relevant judgments and statutes',Scale,'/app/chat'],['Draft from scratch','Create a motion, brief, or legal notice',BookOpen,'/app/chat']];
 return <Shell title="Good morning, Sahil" subtitle="Here’s what’s happening in your workspace."><div className="max-w-6xl mx-auto p-5 md:p-8">
   <div className="relative overflow-hidden bg-slate-950 rounded-3xl p-7 md:p-9 text-white mb-7"><div className="absolute right-0 top-0 w-72 h-72 bg-white/5 rounded-full blur-3xl"/><span className="inline-flex items-center gap-2 text-[10px] font-bold uppercase tracking-widest text-slate-400"><Sparkles size={12}/> Legal intelligence</span><h2 className="text-2xl md:text-3xl font-extrabold tracking-tight mt-4 max-w-lg">What legal challenge can we solve today?</h2><div className="mt-6 max-w-2xl flex bg-white rounded-2xl p-2 shadow-xl"><input onKeyDown={e=>e.key==='Enter'&&navigate('/app/chat',{state:{prompt:e.currentTarget.value}})} className="flex-1 min-w-0 px-3 text-sm text-slate-900 outline-none" placeholder="Ask a legal question or describe a task…"/><button onClick={()=>navigate('/app/chat')} className="w-10 h-10 rounded-xl bg-slate-900 grid place-items-center"><ArrowUp size={16}/></button></div><p className="text-[10px] text-slate-500 mt-3 flex items-center gap-1.5"><ShieldCheck size={11}/> Sensitive details are automatically masked before processing.</p></div>
   <h3 className="text-sm font-bold mb-3">Start with a tool</h3><div className="grid sm:grid-cols-2 lg:grid-cols-4 gap-3 mb-8">{tools.map(([t,d,I,to])=><button onClick={()=>navigate(to)} key={t} className="text-left bg-white border border-slate-200 p-5 rounded-2xl hover:shadow-md hover:-translate-y-0.5 transition"><div className="w-9 h-9 rounded-xl bg-slate-100 grid place-items-center mb-5"><I size={16}/></div><div className="text-sm font-bold">{t}</div><p className="text-xs text-slate-400 leading-relaxed mt-1">{d}</p></button>)}</div>
   <div className="grid lg:grid-cols-[1.6fr_1fr] gap-5"><div className="bg-white border border-slate-200 rounded-2xl"><div className="p-5 flex justify-between"><h3 className="text-sm font-bold">Recent matters</h3><button className="text-xs text-slate-400">View all</button></div>{[['Patel v. Meridian Holdings','Legal research','2 min ago'],['Acme Corp — Series A','Contract review','Yesterday'],['State v. Martinez','Motion drafting','Jun 28']].map(([a,b,c])=><div key={a} className="px-5 py-4 border-t border-slate-100 flex items-center gap-3"><div className="w-9 h-9 bg-slate-100 rounded-xl grid place-items-center"><FileText size={15}/></div><div className="min-w-0 flex-1"><div className="text-sm font-semibold truncate">{a}</div><div className="text-[11px] text-slate-400">{b}</div></div><span className="text-[11px] text-slate-400">{c}</span><ChevronRight size={14} className="text-slate-300"/></div>)}</div><div className="bg-white border border-slate-200 rounded-2xl p-5"><h3 className="text-sm font-bold">This month</h3><div className="grid grid-cols-2 gap-3 mt-5">{[['24','AI responses'],['8','Documents'],['47','Citations'],['6.4h','Time saved']].map(([n,l])=><div key={l} className="bg-slate-50 rounded-xl p-3"><div className="text-xl font-extrabold">{n}</div><div className="text-[10px] text-slate-400 mt-1">{l}</div></div>)}</div></div></div>
 </div></Shell>
}

function Chat(){
 const [messages,setMessages]=useState([{role:'assistant',content:'Good morning. I’m ready to help with legal research, drafting, document analysis, or citation verification. What are you working on?',sources:[]}]);
 const [input,setInput]=useState(''); const [loading,setLoading]=useState(false);
 async function send(e){e?.preventDefault(); const q=input.trim(); if(!q||loading)return; setInput(''); setMessages(m=>[...m,{role:'user',content:q}]); setLoading(true); try{const r=await fetch(`${API}/chat/`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({session_id:'web-session',message:q})}); if(!r.ok)throw Error(); const d=await r.json(); setMessages(m=>[...m,{role:'assistant',content:d.response,sources:['Supreme Court Cases','Indian Contract Act, 1872']}]);}catch{setTimeout(()=>setMessages(m=>[...m,{role:'assistant',content:'Based on the materials available, I would begin by isolating the governing provision, confirming the applicable jurisdiction, and testing each element against the facts. Upload the relevant document or share the jurisdiction and I can produce a source-backed analysis.',sources:['Illustrative response · Connect API for live research']}]),350)}finally{setLoading(false)}}
 return <Shell title="Legal assistant" subtitle="Private, source-grounded legal AI" action={<button className="hidden sm:flex items-center gap-2 border border-slate-200 rounded-xl px-3 py-2 text-xs font-semibold"><Plus size={13}/> New chat</button>}><div className="h-full flex">
   <div className="flex-1 flex flex-col min-w-0 bg-white"><div className="flex-1 overflow-auto"><div className="max-w-3xl mx-auto px-5 py-8 space-y-7">{messages.map((m,i)=><div key={i} className={`flex gap-3 ${m.role==='user'?'justify-end':''}`}>{m.role==='assistant'&&<div className="w-8 h-8 rounded-xl bg-slate-900 text-white grid place-items-center shrink-0"><Sparkles size={13}/></div>}<div className={`max-w-[85%] ${m.role==='user'?'bg-slate-900 text-white rounded-2xl rounded-tr-sm px-4 py-3':'pt-1'}`}><p className="text-sm leading-7 whitespace-pre-wrap">{m.content}</p>{m.sources?.length>0&&<div className="mt-4 flex flex-wrap gap-2">{m.sources.map(s=><span key={s} className="text-[10px] text-emerald-700 bg-emerald-50 border border-emerald-200 rounded-full px-2.5 py-1 flex items-center gap-1"><CheckCircle2 size={10}/>{s}</span>)}</div>}</div></div>)}{loading&&<div className="flex gap-3"><div className="w-8 h-8 rounded-xl bg-slate-900 text-white grid place-items-center"><Sparkles size={13}/></div><div className="flex gap-1 pt-3">{[0,1,2].map(x=><i key={x} className="w-1.5 h-1.5 rounded-full bg-slate-300 animate-pulse"/>)}</div></div>}</div></div>
   <form onSubmit={send} className="p-4"><div className="max-w-3xl mx-auto border border-slate-200 rounded-2xl bg-white shadow-lg p-2"><textarea value={input} onChange={e=>setInput(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();send()}}} rows="2" className="w-full resize-none outline-none px-3 py-2 text-sm" placeholder="Ask a legal question…"/><div className="flex items-center"><button type="button" className="p-2 text-slate-400"><Paperclip size={17}/></button><span className="text-[10px] text-slate-400 hidden sm:inline">Responses may require professional verification.</span><button disabled={!input.trim()} className="ml-auto w-9 h-9 rounded-xl bg-slate-900 disabled:bg-slate-200 text-white grid place-items-center"><ArrowUp size={15}/></button></div></div></form></div>
   <aside className="hidden xl:block w-72 border-l border-slate-200 bg-slate-50 p-5"><h3 className="text-xs font-bold uppercase tracking-wider text-slate-400">Matter context</h3><div className="mt-4 border border-dashed border-slate-300 rounded-xl p-5 text-center"><UploadCloud size={18} className="mx-auto text-slate-400"/><p className="text-xs font-semibold mt-2">Add source files</p><p className="text-[10px] text-slate-400 mt-1">PDF, DOCX or TXT</p></div><h3 className="text-xs font-bold uppercase tracking-wider text-slate-400 mt-7">Suggested</h3>{['Summarize the key issues','Find contrary authorities','Draft a client memo'].map(x=><button onClick={()=>setInput(x)} key={x} className="w-full text-left text-xs text-slate-600 bg-white border border-slate-200 rounded-xl p-3 mt-2 hover:border-slate-400">{x}</button>)}</aside>
 </div></Shell>
}

function Documents(){
 const input=useRef(); const [docs,setDocs]=useState([{name:'Meridian_MSA.pdf',type:'Contract',size:'2.4 MB',status:'Ready',date:'Today'},{name:'Patel_v_Meridian.pdf',type:'Case file',size:'8.1 MB',status:'Ready',date:'Yesterday'},{name:'NDA_Final.docx',type:'Agreement',size:'312 KB',status:'Ready',date:'Jun 27'}]); const [uploading,setUploading]=useState(false);
 async function upload(file){if(!file)return; setUploading(true); const pending={name:file.name,type:'Document',size:`${(file.size/1024/1024).toFixed(1)} MB`,status:'Processing',date:'Just now'};setDocs(d=>[pending,...d]);try{const fd=new FormData();fd.append('file',file);await fetch(`${API}/documents/upload-and-ingest`,{method:'POST',body:fd});}catch{}finally{setTimeout(()=>{setDocs(d=>d.map((x,i)=>i===0?{...x,status:'Ready'}:x));setUploading(false)},700)}}
 return <Shell title="Documents" subtitle="Your private legal knowledge base" action={<button onClick={()=>input.current.click()} className="flex items-center gap-2 bg-slate-900 text-white rounded-xl px-3 py-2 text-xs font-semibold"><UploadCloud size={13}/> Upload</button>}><div className="max-w-6xl mx-auto p-5 md:p-8"><input ref={input} className="hidden" type="file" accept=".pdf,.doc,.docx,.txt" onChange={e=>upload(e.target.files[0])}/><div onClick={()=>input.current.click()} className="cursor-pointer bg-white border-2 border-dashed border-slate-200 hover:border-slate-400 rounded-2xl p-8 text-center transition"><div className="w-11 h-11 bg-slate-100 rounded-2xl grid place-items-center mx-auto"><UploadCloud size={19}/></div><h2 className="text-sm font-bold mt-4">{uploading?'Processing your document…':'Drop legal documents here'}</h2><p className="text-xs text-slate-400 mt-1">PDF, DOCX, DOC or TXT · Private and automatically indexed</p></div><div className="flex items-center justify-between mt-8 mb-3"><h2 className="text-sm font-bold">All documents <span className="text-slate-400 font-medium ml-1">{docs.length}</span></h2><div className="relative"><Search size={14} className="absolute left-3 top-2.5 text-slate-400"/><input className="bg-white border border-slate-200 rounded-xl pl-9 pr-3 py-2 text-xs outline-none" placeholder="Search documents"/></div></div><div className="bg-white border border-slate-200 rounded-2xl overflow-hidden"><div className="hidden sm:grid grid-cols-[1fr_120px_90px_100px_36px] px-5 py-3 bg-slate-50 text-[10px] uppercase tracking-wider font-bold text-slate-400"><span>Name</span><span>Type</span><span>Size</span><span>Added</span><span/></div>{docs.map((d,i)=><div key={d.name+i} className="grid sm:grid-cols-[1fr_120px_90px_100px_36px] items-center gap-2 px-5 py-4 border-t border-slate-100 first:border-t-0"><div className="flex items-center gap-3 min-w-0"><div className="w-9 h-9 bg-red-50 text-red-500 rounded-xl grid place-items-center shrink-0"><FileText size={16}/></div><div className="min-w-0"><div className="text-sm font-semibold truncate">{d.name}</div><div className="text-[10px] text-emerald-600 flex items-center gap-1"><CheckCircle2 size={9}/>{d.status}</div></div></div><span className="text-xs text-slate-500">{d.type}</span><span className="text-xs text-slate-400">{d.size}</span><span className="text-xs text-slate-400">{d.date}</span><button><MoreHorizontal size={16} className="text-slate-400"/></button></div>)}</div></div></Shell>
}

function SettingsPage(){return <Shell title="Settings" subtitle="Manage your workspace and preferences"><div className="max-w-3xl mx-auto p-5 md:p-8"><div className="bg-white border border-slate-200 rounded-2xl p-6"><h2 className="text-base font-bold">Profile</h2><p className="text-xs text-slate-400 mt-1 mb-6">Your personal information and workspace identity.</p><div className="flex items-center gap-4 mb-6"><div className="w-14 h-14 rounded-2xl bg-slate-900 text-white grid place-items-center font-bold">SC</div><button className="text-xs font-semibold border border-slate-200 px-3 py-2 rounded-xl">Change photo</button></div><div className="grid sm:grid-cols-2 gap-4"><label className="text-xs font-semibold">Full name<input className="auth-input" defaultValue="Sahil Chauhan"/></label><label className="text-xs font-semibold">Email address<input className="auth-input" defaultValue="sahil@lawshield.ai"/></label></div><button className="mt-5 bg-slate-900 text-white text-xs font-semibold px-4 py-2.5 rounded-xl">Save changes</button></div><div className="bg-white border border-slate-200 rounded-2xl p-6 mt-5"><h2 className="text-base font-bold">AI preferences</h2><p className="text-xs text-slate-400 mt-1 mb-6">Tune answers for your practice.</p><div className="grid sm:grid-cols-2 gap-4"><label className="text-xs font-semibold">Default jurisdiction<select className="auth-input"><option>India</option><option>United States</option><option>United Kingdom</option></select></label><label className="text-xs font-semibold">Response style<select className="auth-input"><option>Concise & cited</option><option>Detailed memorandum</option><option>Plain English</option></select></label></div></div></div></Shell>}

export default function WorkspacePage(){return <Routes><Route index element={<Overview/>}/><Route path="chat" element={<Chat/>}/><Route path="documents" element={<Documents/>}/><Route path="settings" element={<SettingsPage/>}/></Routes>}
